#SConstruct

import os,platform
#rsfroot=os.environ.get('RSFSRC')
prod_dir=os.environ.get('PROD_DIR')
cwproot=os.environ.get('CWPROOT')

installdir = ['../bin']

progs='''
swcdmod2
swcdmod2ht
'''

libs = Split("""mkl_intel_ilp64 mkl_intel_thread mkl_core iomp5 pthread
	su par cwp m""")

libpath = [prod_dir+'/mkl/lib/intel64', \
		   prod_dir+'/compiler/lib/intel64', \
		   cwproot+'/lib' \
		   ]

include = [prod_dir+'/mkl/include', \
		   cwproot+'/src/Complex/include', \
		   cwproot+'/include' \
		   ]

env=Environment()
env.Prepend(LIBPATH=libpath, CPPPATH=include, LIBS=libs)
env.Replace(CXX=prod_dir+'/bin/icpc', CCFLAGS='-O2')
env.Replace(CC=prod_dir+'/bin/icc', CCFLAGS='-O2')

mains = Split(progs)
for prog in mains:
	prog = env.Program([prog + '.c', 'cdcoeff.c'])
	env.Install(installdir, prog)

env.Alias('install', installdir)
